# Generated by Django 2.1.2 on 2018-10-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0002_auto_20181029_1853'),
        ('motorcycle', '0002_transaction'),
    ]

    operations = [
    ]
